// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: parameters.proto

package com.parameters;

public final class Parameters {
  private Parameters() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface parametersOrBuilder extends
      // @@protoc_insertion_point(interface_extends:parameters.parameters)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 image_dimension = 1;</code>
     */
    boolean hasImageDimension();
    /**
     * <code>required uint32 image_dimension = 1;</code>
     */
    int getImageDimension();

    /**
     * <code>required uint32 kernel_dimension = 2;</code>
     */
    boolean hasKernelDimension();
    /**
     * <code>required uint32 kernel_dimension = 2;</code>
     */
    int getKernelDimension();
  }
  /**
   * Protobuf type {@code parameters.parameters}
   */
  public  static final class parameters extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:parameters.parameters)
      parametersOrBuilder {
    // Use parameters.newBuilder() to construct.
    private parameters(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private parameters() {
      imageDimension_ = 0;
      kernelDimension_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private parameters(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              imageDimension_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              kernelDimension_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.parameters.Parameters.internal_static_parameters_parameters_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.parameters.Parameters.internal_static_parameters_parameters_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.parameters.Parameters.parameters.class, com.parameters.Parameters.parameters.Builder.class);
    }

    private int bitField0_;
    public static final int IMAGE_DIMENSION_FIELD_NUMBER = 1;
    private int imageDimension_;
    /**
     * <code>required uint32 image_dimension = 1;</code>
     */
    public boolean hasImageDimension() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 image_dimension = 1;</code>
     */
    public int getImageDimension() {
      return imageDimension_;
    }

    public static final int KERNEL_DIMENSION_FIELD_NUMBER = 2;
    private int kernelDimension_;
    /**
     * <code>required uint32 kernel_dimension = 2;</code>
     */
    public boolean hasKernelDimension() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 kernel_dimension = 2;</code>
     */
    public int getKernelDimension() {
      return kernelDimension_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasImageDimension()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasKernelDimension()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, imageDimension_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, kernelDimension_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, imageDimension_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, kernelDimension_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.parameters.Parameters.parameters)) {
        return super.equals(obj);
      }
      com.parameters.Parameters.parameters other = (com.parameters.Parameters.parameters) obj;

      boolean result = true;
      result = result && (hasImageDimension() == other.hasImageDimension());
      if (hasImageDimension()) {
        result = result && (getImageDimension()
            == other.getImageDimension());
      }
      result = result && (hasKernelDimension() == other.hasKernelDimension());
      if (hasKernelDimension()) {
        result = result && (getKernelDimension()
            == other.getKernelDimension());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasImageDimension()) {
        hash = (37 * hash) + IMAGE_DIMENSION_FIELD_NUMBER;
        hash = (53 * hash) + getImageDimension();
      }
      if (hasKernelDimension()) {
        hash = (37 * hash) + KERNEL_DIMENSION_FIELD_NUMBER;
        hash = (53 * hash) + getKernelDimension();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.parameters.Parameters.parameters parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.parameters.Parameters.parameters parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.parameters.Parameters.parameters parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.parameters.Parameters.parameters parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.parameters.Parameters.parameters parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.parameters.Parameters.parameters parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.parameters.Parameters.parameters parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.parameters.Parameters.parameters parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.parameters.Parameters.parameters parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.parameters.Parameters.parameters parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.parameters.Parameters.parameters prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code parameters.parameters}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:parameters.parameters)
        com.parameters.Parameters.parametersOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.parameters.Parameters.internal_static_parameters_parameters_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.parameters.Parameters.internal_static_parameters_parameters_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.parameters.Parameters.parameters.class, com.parameters.Parameters.parameters.Builder.class);
      }

      // Construct using com.parameters.Parameters.parameters.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        imageDimension_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        kernelDimension_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.parameters.Parameters.internal_static_parameters_parameters_descriptor;
      }

      public com.parameters.Parameters.parameters getDefaultInstanceForType() {
        return com.parameters.Parameters.parameters.getDefaultInstance();
      }

      public com.parameters.Parameters.parameters build() {
        com.parameters.Parameters.parameters result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.parameters.Parameters.parameters buildPartial() {
        com.parameters.Parameters.parameters result = new com.parameters.Parameters.parameters(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.imageDimension_ = imageDimension_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.kernelDimension_ = kernelDimension_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.parameters.Parameters.parameters) {
          return mergeFrom((com.parameters.Parameters.parameters)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.parameters.Parameters.parameters other) {
        if (other == com.parameters.Parameters.parameters.getDefaultInstance()) return this;
        if (other.hasImageDimension()) {
          setImageDimension(other.getImageDimension());
        }
        if (other.hasKernelDimension()) {
          setKernelDimension(other.getKernelDimension());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasImageDimension()) {
          return false;
        }
        if (!hasKernelDimension()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.parameters.Parameters.parameters parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.parameters.Parameters.parameters) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int imageDimension_ ;
      /**
       * <code>required uint32 image_dimension = 1;</code>
       */
      public boolean hasImageDimension() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 image_dimension = 1;</code>
       */
      public int getImageDimension() {
        return imageDimension_;
      }
      /**
       * <code>required uint32 image_dimension = 1;</code>
       */
      public Builder setImageDimension(int value) {
        bitField0_ |= 0x00000001;
        imageDimension_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 image_dimension = 1;</code>
       */
      public Builder clearImageDimension() {
        bitField0_ = (bitField0_ & ~0x00000001);
        imageDimension_ = 0;
        onChanged();
        return this;
      }

      private int kernelDimension_ ;
      /**
       * <code>required uint32 kernel_dimension = 2;</code>
       */
      public boolean hasKernelDimension() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 kernel_dimension = 2;</code>
       */
      public int getKernelDimension() {
        return kernelDimension_;
      }
      /**
       * <code>required uint32 kernel_dimension = 2;</code>
       */
      public Builder setKernelDimension(int value) {
        bitField0_ |= 0x00000002;
        kernelDimension_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 kernel_dimension = 2;</code>
       */
      public Builder clearKernelDimension() {
        bitField0_ = (bitField0_ & ~0x00000002);
        kernelDimension_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:parameters.parameters)
    }

    // @@protoc_insertion_point(class_scope:parameters.parameters)
    private static final com.parameters.Parameters.parameters DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.parameters.Parameters.parameters();
    }

    public static com.parameters.Parameters.parameters getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<parameters>
        PARSER = new com.google.protobuf.AbstractParser<parameters>() {
      public parameters parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new parameters(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<parameters> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<parameters> getParserForType() {
      return PARSER;
    }

    public com.parameters.Parameters.parameters getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface layerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:parameters.layer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .parameters.parameters p = 1;</code>
     */
    java.util.List<com.parameters.Parameters.parameters> 
        getPList();
    /**
     * <code>repeated .parameters.parameters p = 1;</code>
     */
    com.parameters.Parameters.parameters getP(int index);
    /**
     * <code>repeated .parameters.parameters p = 1;</code>
     */
    int getPCount();
    /**
     * <code>repeated .parameters.parameters p = 1;</code>
     */
    java.util.List<? extends com.parameters.Parameters.parametersOrBuilder> 
        getPOrBuilderList();
    /**
     * <code>repeated .parameters.parameters p = 1;</code>
     */
    com.parameters.Parameters.parametersOrBuilder getPOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code parameters.layer}
   */
  public  static final class layer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:parameters.layer)
      layerOrBuilder {
    // Use layer.newBuilder() to construct.
    private layer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private layer() {
      p_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private layer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                p_ = new java.util.ArrayList<com.parameters.Parameters.parameters>();
                mutable_bitField0_ |= 0x00000001;
              }
              p_.add(
                  input.readMessage(com.parameters.Parameters.parameters.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          p_ = java.util.Collections.unmodifiableList(p_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.parameters.Parameters.internal_static_parameters_layer_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.parameters.Parameters.internal_static_parameters_layer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.parameters.Parameters.layer.class, com.parameters.Parameters.layer.Builder.class);
    }

    public static final int P_FIELD_NUMBER = 1;
    private java.util.List<com.parameters.Parameters.parameters> p_;
    /**
     * <code>repeated .parameters.parameters p = 1;</code>
     */
    public java.util.List<com.parameters.Parameters.parameters> getPList() {
      return p_;
    }
    /**
     * <code>repeated .parameters.parameters p = 1;</code>
     */
    public java.util.List<? extends com.parameters.Parameters.parametersOrBuilder> 
        getPOrBuilderList() {
      return p_;
    }
    /**
     * <code>repeated .parameters.parameters p = 1;</code>
     */
    public int getPCount() {
      return p_.size();
    }
    /**
     * <code>repeated .parameters.parameters p = 1;</code>
     */
    public com.parameters.Parameters.parameters getP(int index) {
      return p_.get(index);
    }
    /**
     * <code>repeated .parameters.parameters p = 1;</code>
     */
    public com.parameters.Parameters.parametersOrBuilder getPOrBuilder(
        int index) {
      return p_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getPCount(); i++) {
        if (!getP(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < p_.size(); i++) {
        output.writeMessage(1, p_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < p_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, p_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.parameters.Parameters.layer)) {
        return super.equals(obj);
      }
      com.parameters.Parameters.layer other = (com.parameters.Parameters.layer) obj;

      boolean result = true;
      result = result && getPList()
          .equals(other.getPList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getPCount() > 0) {
        hash = (37 * hash) + P_FIELD_NUMBER;
        hash = (53 * hash) + getPList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.parameters.Parameters.layer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.parameters.Parameters.layer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.parameters.Parameters.layer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.parameters.Parameters.layer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.parameters.Parameters.layer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.parameters.Parameters.layer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.parameters.Parameters.layer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.parameters.Parameters.layer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.parameters.Parameters.layer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.parameters.Parameters.layer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.parameters.Parameters.layer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code parameters.layer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:parameters.layer)
        com.parameters.Parameters.layerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.parameters.Parameters.internal_static_parameters_layer_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.parameters.Parameters.internal_static_parameters_layer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.parameters.Parameters.layer.class, com.parameters.Parameters.layer.Builder.class);
      }

      // Construct using com.parameters.Parameters.layer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (pBuilder_ == null) {
          p_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          pBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.parameters.Parameters.internal_static_parameters_layer_descriptor;
      }

      public com.parameters.Parameters.layer getDefaultInstanceForType() {
        return com.parameters.Parameters.layer.getDefaultInstance();
      }

      public com.parameters.Parameters.layer build() {
        com.parameters.Parameters.layer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.parameters.Parameters.layer buildPartial() {
        com.parameters.Parameters.layer result = new com.parameters.Parameters.layer(this);
        int from_bitField0_ = bitField0_;
        if (pBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            p_ = java.util.Collections.unmodifiableList(p_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.p_ = p_;
        } else {
          result.p_ = pBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.parameters.Parameters.layer) {
          return mergeFrom((com.parameters.Parameters.layer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.parameters.Parameters.layer other) {
        if (other == com.parameters.Parameters.layer.getDefaultInstance()) return this;
        if (pBuilder_ == null) {
          if (!other.p_.isEmpty()) {
            if (p_.isEmpty()) {
              p_ = other.p_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePIsMutable();
              p_.addAll(other.p_);
            }
            onChanged();
          }
        } else {
          if (!other.p_.isEmpty()) {
            if (pBuilder_.isEmpty()) {
              pBuilder_.dispose();
              pBuilder_ = null;
              p_ = other.p_;
              bitField0_ = (bitField0_ & ~0x00000001);
              pBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPFieldBuilder() : null;
            } else {
              pBuilder_.addAllMessages(other.p_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getPCount(); i++) {
          if (!getP(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.parameters.Parameters.layer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.parameters.Parameters.layer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.parameters.Parameters.parameters> p_ =
        java.util.Collections.emptyList();
      private void ensurePIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          p_ = new java.util.ArrayList<com.parameters.Parameters.parameters>(p_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.parameters.Parameters.parameters, com.parameters.Parameters.parameters.Builder, com.parameters.Parameters.parametersOrBuilder> pBuilder_;

      /**
       * <code>repeated .parameters.parameters p = 1;</code>
       */
      public java.util.List<com.parameters.Parameters.parameters> getPList() {
        if (pBuilder_ == null) {
          return java.util.Collections.unmodifiableList(p_);
        } else {
          return pBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .parameters.parameters p = 1;</code>
       */
      public int getPCount() {
        if (pBuilder_ == null) {
          return p_.size();
        } else {
          return pBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .parameters.parameters p = 1;</code>
       */
      public com.parameters.Parameters.parameters getP(int index) {
        if (pBuilder_ == null) {
          return p_.get(index);
        } else {
          return pBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .parameters.parameters p = 1;</code>
       */
      public Builder setP(
          int index, com.parameters.Parameters.parameters value) {
        if (pBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePIsMutable();
          p_.set(index, value);
          onChanged();
        } else {
          pBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .parameters.parameters p = 1;</code>
       */
      public Builder setP(
          int index, com.parameters.Parameters.parameters.Builder builderForValue) {
        if (pBuilder_ == null) {
          ensurePIsMutable();
          p_.set(index, builderForValue.build());
          onChanged();
        } else {
          pBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .parameters.parameters p = 1;</code>
       */
      public Builder addP(com.parameters.Parameters.parameters value) {
        if (pBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePIsMutable();
          p_.add(value);
          onChanged();
        } else {
          pBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .parameters.parameters p = 1;</code>
       */
      public Builder addP(
          int index, com.parameters.Parameters.parameters value) {
        if (pBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePIsMutable();
          p_.add(index, value);
          onChanged();
        } else {
          pBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .parameters.parameters p = 1;</code>
       */
      public Builder addP(
          com.parameters.Parameters.parameters.Builder builderForValue) {
        if (pBuilder_ == null) {
          ensurePIsMutable();
          p_.add(builderForValue.build());
          onChanged();
        } else {
          pBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .parameters.parameters p = 1;</code>
       */
      public Builder addP(
          int index, com.parameters.Parameters.parameters.Builder builderForValue) {
        if (pBuilder_ == null) {
          ensurePIsMutable();
          p_.add(index, builderForValue.build());
          onChanged();
        } else {
          pBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .parameters.parameters p = 1;</code>
       */
      public Builder addAllP(
          java.lang.Iterable<? extends com.parameters.Parameters.parameters> values) {
        if (pBuilder_ == null) {
          ensurePIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, p_);
          onChanged();
        } else {
          pBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .parameters.parameters p = 1;</code>
       */
      public Builder clearP() {
        if (pBuilder_ == null) {
          p_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          pBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .parameters.parameters p = 1;</code>
       */
      public Builder removeP(int index) {
        if (pBuilder_ == null) {
          ensurePIsMutable();
          p_.remove(index);
          onChanged();
        } else {
          pBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .parameters.parameters p = 1;</code>
       */
      public com.parameters.Parameters.parameters.Builder getPBuilder(
          int index) {
        return getPFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .parameters.parameters p = 1;</code>
       */
      public com.parameters.Parameters.parametersOrBuilder getPOrBuilder(
          int index) {
        if (pBuilder_ == null) {
          return p_.get(index);  } else {
          return pBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .parameters.parameters p = 1;</code>
       */
      public java.util.List<? extends com.parameters.Parameters.parametersOrBuilder> 
           getPOrBuilderList() {
        if (pBuilder_ != null) {
          return pBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(p_);
        }
      }
      /**
       * <code>repeated .parameters.parameters p = 1;</code>
       */
      public com.parameters.Parameters.parameters.Builder addPBuilder() {
        return getPFieldBuilder().addBuilder(
            com.parameters.Parameters.parameters.getDefaultInstance());
      }
      /**
       * <code>repeated .parameters.parameters p = 1;</code>
       */
      public com.parameters.Parameters.parameters.Builder addPBuilder(
          int index) {
        return getPFieldBuilder().addBuilder(
            index, com.parameters.Parameters.parameters.getDefaultInstance());
      }
      /**
       * <code>repeated .parameters.parameters p = 1;</code>
       */
      public java.util.List<com.parameters.Parameters.parameters.Builder> 
           getPBuilderList() {
        return getPFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.parameters.Parameters.parameters, com.parameters.Parameters.parameters.Builder, com.parameters.Parameters.parametersOrBuilder> 
          getPFieldBuilder() {
        if (pBuilder_ == null) {
          pBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.parameters.Parameters.parameters, com.parameters.Parameters.parameters.Builder, com.parameters.Parameters.parametersOrBuilder>(
                  p_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          p_ = null;
        }
        return pBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:parameters.layer)
    }

    // @@protoc_insertion_point(class_scope:parameters.layer)
    private static final com.parameters.Parameters.layer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.parameters.Parameters.layer();
    }

    public static com.parameters.Parameters.layer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<layer>
        PARSER = new com.google.protobuf.AbstractParser<layer>() {
      public layer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new layer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<layer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<layer> getParserForType() {
      return PARSER;
    }

    public com.parameters.Parameters.layer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_parameters_parameters_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_parameters_parameters_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_parameters_layer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_parameters_layer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020parameters.proto\022\nparameters\"?\n\nparame" +
      "ters\022\027\n\017image_dimension\030\001 \002(\r\022\030\n\020kernel_" +
      "dimension\030\002 \002(\r\"*\n\005layer\022!\n\001p\030\001 \003(\0132\026.pa" +
      "rameters.parametersB\034\n\016com.parametersB\nP" +
      "arameters"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_parameters_parameters_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_parameters_parameters_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_parameters_parameters_descriptor,
        new java.lang.String[] { "ImageDimension", "KernelDimension", });
    internal_static_parameters_layer_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_parameters_layer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_parameters_layer_descriptor,
        new java.lang.String[] { "P", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
